@startuml
!define table(x) class x << (T,#FFAAAA) >>
!define primaryKey(x) <u>x</u>
!define foreignKey(x) <i>x</i>

' === Tables ===
table(hero_sections) {
  primaryKey(hero_section_id): INT
  achievement: VARCHAR
  heading: VARCHAR
  subheading: VARCHAR
  path_video: VARCHAR
  banner: VARCHAR
}

table(project_clients) {
  primaryKey(project_client_id): INT
  foreignKey(user_id): INT
  name: VARCHAR
  occupation: VARCHAR
  avatar: VARCHAR
  logo: VARCHAR
}

table(profile) {
  primaryKey(id_admin): INT
  username: VARCHAR
  password: VARCHAR
  name: VARCHAR
}

table(users) {
  primaryKey(user_id): INT
  email: VARCHAR
  email_verified_at: TIME
  password: VARCHAR
}

table(our_principles) {
  primaryKey(principle_id): INT
  name: VARCHAR
  subtitle: VARCHAR
  thumbnail: VARCHAR
  icon: VARCHAR
}

table(company_abouts) {
  primaryKey(company_about_id): INT
  name: VARCHAR
  thumbnail: VARCHAR
  type: VARCHAR
}

table(company_statistics) {
  primaryKey(id): INT
  name: VARCHAR
  goal: VARCHAR
  icon: VARCHAR
}

table(company_key_points) {
  primaryKey(company_key_points_id): INT
  foreignKey(company_about_id): INT
}

table(appointments) {
  primaryKey(appointment_id): INT
  foreignKey(user_id): INT
  foreignKey(product_id): INT
  name: VARCHAR
  email: VARCHAR
  status: VARCHAR
  brief: VARCHAR
  phone: VARCHAR
}

table(testimonials) {
  primaryKey(testimoni_id): INT
  foreignKey(id_client): INT
  thumbnail: VARCHAR
  message: VARCHAR
}

table(our_teams) {
  primaryKey(team_id): INT
  occupation: VARCHAR
  avatar: VARCHAR
  location: VARCHAR
}

table(products) {
  primaryKey(product_id): INT
  name: VARCHAR
  tagline: VARCHAR
  thumbnail: VARCHAR
  about: VARCHAR
}

table(galleries) {
  primaryKey(galery_id): INT
  title: VARCHAR
  image: VARCHAR
  description: VARCHAR
}

table(awards) {
  primaryKey(award_id): INT
  title: VARCHAR
  year: YEAR
  icon: VARCHAR
  location: VARCHAR
}

' === Relationships ===
users ||--o{ appointments
users ||--o{ project_clients
project_clients ||--o{ testimonials
products ||--o{ appointments
company_abouts ||--o{ company_key_points
@enduml
