@startuml
|User|
start
:Masuk Website ;
:Klik Menu Appointment;
if (             Alert
(buat appointments?)) then (Ya)
  :Dialihkan ke halaman Login;
  :Login/register;
else (Tidak)
  stop;
endif

|System|
:Menampilkan halaman login/register;

|User|
:Login / Registrasi;

|System|
:Autentikasi User;

|User|
:Isi Form Usulan;
:Klik Submit;

|System|
:Validasi Form;
:Masuk ke Halaman Tracking;
:Set Status = Pending;

|User|
:Menentukan Jadwal Meeting;

|Admin|
:Melihat Data Usulan Baru;
:Update Status Menjadi
    "Disetujui/ditolak";

|System|
:Update Status Ke Sistem;

|User|
:Melihat Status Terkini;

stop
@enduml
